spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    password: WINner0315
    diver-class-name: com.mysql.cj.jdbc.Driver


